/* eslint-disable @typescript-eslint/no-unused-vars */
const lol = {
  type: 'customer',
  supplier_business_name: 'samer fadi',
  prefix: 'mr',
  first_name: 'ebrahem',
  middle_name: '',
  last_name: 'sai',
  tax_number: '021454541200',
  pay_term_number: '',
  pay_term_type: '',
  mobile: '0501744414',
  landline: '0412471',
  alternate_number: '',
  city: 'dubai',
  state: 'almoraqqabat',
  country: 'Emerat',
  address_line_1: '',
  address_line_2: '',
  customer_group_id: '2',
  zip_code: '11122221',
  contact_id: '',
  custom_field1: '3432',
  custom_field2: '123',
  custom_field3: '342',
  custom_field4: '321',
  custom_field5: '21',
  custom_field6: '32',
  custom_field7: '32',
  custom_field8: '2',
  custom_field9: '31',
  custom_field10: '221',
  email: 'samer@gmail.com',
  shipping_address: 'dubai 123',
  position: 'dubai',
  dob: '2000-10-03',
  credit_limit: 'dubai',
  opening_balance: '1000'
}
