/* eslint-disable @typescript-eslint/no-unused-vars */
const lol = {
  type: 'supplier',
  supplier_business_name: 'Helwan University',
  prefix: 'Mr.',
  first_name: 'Ali',
  middle_name: 'sd',
  last_name: 'Hatem',
  tax_number: 'qw',
  pay_term_number: '34',
  pay_term_type: 'days',
  mobile: '1026159353',
  landline: '12',
  alternate_number: '1026159353',
  city: 'Giza',
  state: 'Qanater facility',
  country: 'Egypt',
  address_line_1: 'Egypt | Giza | The origin of the Qanater | BaHarmes',
  address_line_2: 'sssssssssss',
  customer_group_id: '',
  zip_code: '12966',
  contact_id: '',
  custom_field1: 'wewe',
  custom_field2: 'dfsdf',
  custom_field3: 'dsd',
  custom_field4: 'sdfsdf',
  custom_field5: 'sdfsdf',
  custom_field6: 'sdfsdf',
  custom_field7: 'sdfsdf',
  custom_field8: 'sdfs',
  custom_field9: 'sdfsd',
  custom_field10: 'sdf',
  email: 'alihatem7201738@gmail.com',
  shipping_address: 'Egypt/Giza/The origin of the Qanater/BaHarmes',
  position: '',
  dob: '11-18-2023',
  credit_limit: '',
  opening_balance: 'qw'
}
